videosweb/catalogo/urls.py
#from django.conf.urls import url

from django.urls import path

from django.urls import re_path as url

from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('videos/', views.BookListView.as_view(), name='videos'),
	path('video/<int:pk>', views.BookDetailView.as_view(), name='video-detail'),
]

videosweb/videosweb/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalogo applications
from django.urls import include

urlpatterns += [
    path('catalogo/', include('catalogo.urls')),
]

#Add URL maps to redirect the base URL to our application

from django.views.generic import RedirectView

urlpatterns += [
    path('', RedirectView.as_view(url='/catalogo/', permanent=True)),
]

#Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

videosweb/catalogo/models.py
from django.db import models

# Create your models here.

class Genre(models.Model):
    """Modelo que representa una descripcion del tipo de video (p. ej. Fam. Torres Cuevas, Fam. Gonzalez Torres, Cumpleanos, Don Chuy, etc.)."""
    nombre = models.CharField(max_length=200, help_text="Ingrese el nombre del tipo de video (p. ej. Fam. Gonzalez Torres, Cumpleanos, etc.)")


    def __str__(self):
        """Cadena que representa a la instancia particular del modelo (p. ej. en el sitio de Administracion)"""

        return self.nombre

from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Video(models.Model):
    """Modelo que representa un video (pero no un video especifico)."""

    titulo = models.CharField(max_length=200)

    autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True)
    # ForeignKey, ya que un libro tiene un solo autor, pero el mismo autor puede haber escrito muchos libros.
    # 'Autor' es un string, en vez de un objeto, porque la clase Author aun no ha sido declarada.

    resumen = models.TextField(max_length=1000, help_text="Ingrese una breve descripcion del video")

    genero = models.ManyToManyField(Genre, help_text="Seleccione un genero para este video")
    # ManyToManyField, porque un genero puede contener muchos videos y un video puede cubrir varios generos.
    # La clase Genre ya ha sido definida, entonces podemos especificar el objeto arriba.

    def __str__(self):
        """String que representa al objeto Video"""
        return self.titulo


    def get_absolute_url(self):
        """Devuelve el URL a una instancia particular de Video"""
        return reverse('video-detail', args=[str(self.id)])

import uuid # Requerida para las instancias de libros unicos

class VideoInstancia(models.Model):
    """Modelo que representa una copia especifica de un video (i.e. que puede ser prestado por la biblioteca de videos)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID unico para este video particular en toda la biblioteca")
    video = models.ForeignKey('Video', on_delete=models.SET_NULL, null=True)

    LOAN_STATUS = (
        ('m', 'Mantenimiento'),
        ('o', 'Viendo'),
        ('a', 'Disponible'),
        ('r', 'Reservado'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Disponibilidad del video')

    class Meta:
        ordering = ["video"]


    def __str__(self):
        """String para representar el Objeto del Modelo"""
        return '%s (%s)' % (self.id,self.video.titulo)

class Autor(models.Model):
    """Modelo que representa un autor"""
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    fecha_de_nacimiento = models.DateField(null=True, blank=True)

    def get_absolute_url(self):
        """Retorna la url para acceder a una instancia particular de un autor."""
        return reverse('autor-detail', args=[str(self.id)])


    def __str__(self):
        """String para representar el Objeto Modelo"""
        return '%s, %s' % (self.nombre, self.apellidos)

videosweb/catalogo/views.py
from django.shortcuts import render

# Create your views here.

from .models import Video, Autor, VideoInstancia, Genre

def index(request):
    """
    Función vista para la página inicio del sitio.
    """
    # Genera contadores de algunos de los objetos principales
    num_books=Video.objects.all().count()
    num_instances=VideoInstancia.objects.all().count()
    # Videos disponibles (status = 'a')
    num_instances_available=VideoInstancia.objects.filter(status__exact='a').count()
    num_authors=Autor.objects.count()  # El 'all()' esta implícito por defecto.

    # Renderiza la plantilla HTML index.html con los datos en la variable contexto
    return render(
        request,
        'index.html',
        context={'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_authors':num_authors},
    )

from django.views import generic

class BookListView(generic.ListView):
    model = Video

class BookDetailView(generic.DetailView):
    model = Video

videosweb/catalogo/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Biblioteca Familiar</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'videos' %}">Todos los videos</a></li>
          <li><a href="">Todos los autores</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

videosweb/catalogo/templates/catalogo/video_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Titulo: {{ video.titulo }}</h1>

   <p><strong>Autor:</strong> <a href="">{{ video.autor }}</a></p> <!-- enlace de detalle del autor aún no definido -->
  <p><strong>Resumen:</strong> {{ video.resumen }}</p>
  <p><strong>Genero:</strong> {% for genre in video.genero.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copias</h4>

    {% for copy in video.videoinstancia_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Pendiente de devolución:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprimir:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>

  {% load static %}

  <video 
    {% if video.titulo == 'Baile_Rogers_Jessica_Primaria' %}
      width="640" height="480" controls><source src="{% static 'videos/Baile_Rogers_Jessica_Primaria.mp4' %}" type="video/mp4">    
    {% endif %}

    {% if video.titulo == 'Cumple_Jessica4' %}
      width="640" height="480" controls><source src="{% static 'videos/Cumple_Jessica4.mp4' %}" type="video/mp4">    
    {% endif %}

    {% if video.titulo == 'Cumple_Quique_Jhonny_Peter_Tampico' %}
      width="640" height="480" controls><source src="{% static 'videos/Cumple_Quique_Jhonny_Peter_Tampico.mp4' %}" type="video/mp4">    
    {% endif %}

    {% if video.titulo == 'Cumple_Quique7_Jhony4' %}
      width="640" height="480" controls><source src="{% static 'videos/Cumple_Quique7_Jhony4.mp4' %}" type="video/mp4">    
    {% endif %}

    {% if video.titulo == 'Cumple_Tina_Casa_Tampico' %}
      width="640" height="480" controls><source src="{% static 'videos/Cumple_Tina_Casa_Tampico.mp4' %}" type="video/mp4">    
    {% endif %}

    {% if video.titulo == 'Fiesta_Graduacion_Kinder_Jessica' %}
      width="640" height="480" controls><source src="{% static 'videos/Fiesta_Graduacion_Kinder_Jessica.mp4' %}" type="video/mp4">    
    {% endif %}

    {% if video.titulo == 'Fin_Anio_Ebano_Casa_Tina' %}
      width="640" height="480" controls><source src="{% static 'videos/Fin_Anio_Ebano_Casa_Tina.mp4' %}" type="video/mp4">    
    {% endif %}

    {% if video.titulo == 'Pastel_Cumple_jlglzd_Tampico' %}
      width="640" height="480" controls><source src="{% static 'videos/Pastel_Cumple_jlglzd_Tampico.mp4' %}" type="video/mp4">    
    {% endif %}

    {% if video.titulo == 'Video_Siglo_XXI_Tsunami' %}
      width="640" height="480" controls><source src="{% static 'videos/Video_Siglo_XXI_Tsunami.mp4' %}" type="video/mp4">    
    {% endif %}
  </video>


{% endblock %}

videosweb/catalogo/templates/catalogo/video_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Lista de videos</h1>

    {% if video_list %}
    <ul>

      {% for video in video_list %}
      <li>
        <a href="{{ video.get_absolute_url }}">{{ video.titulo }}</a> ({{video.autor}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>No hay videos en la biblioteca.</p>
    {% endif %}
{% endblock %}

videosweb/catalogo/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Videos Familiares</h1>

  <p>Bienvenido a <em>Videos Web</em>, una muestra de historias familiares.</p>

<h2>Contenido</h2>

  <p>La biblioteca de videos contiene lo siguiente:</p>
  <ul>
    <li><strong>Videos:</strong> {{ num_books }}</li>
    <li><strong>Copias:</strong> {{ num_instances }}</li>
    <li><strong>Copias disponibles:</strong> {{ num_instances_available }}</li>
    <li><strong>Autores:</strong> {{ num_authors }}</li>
  </ul>

{% endblock %}